# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-format
        additional_dependencies: [clang-format==16.0.6]
        files: \.(c|cpp|h|hpp)$
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        types: [python]
-   repo: ssh://git@github.com/Software-GCAI/precommit-scripts
    rev: v1.0.1
    hooks:
    -   id: gc-copyright
