// Copyright (c) 2020 Graphcore Ltd. All rights reserved.
#ifndef POPART_WILLOW_INCLUDE_POPART_POPX_DEBUGCONTEXTX_HPP_
#define POPART_WILLOW_INCLUDE_POPART_POPX_DEBUGCONTEXTX_HPP_

#include <poplar/DebugContext.hpp>

#endif // POPART_WILLOW_INCLUDE_POPART_POPX_DEBUGCONTEXTX_HPP_
