// Copyright (c) 2018 Graphcore Ltd. All rights reserved.
/*
 * THIS IS AN AUTOGENERATED FILE, DO NOT EDIT DIRECTLY
 *
 * To regenerate this file run the gen_operators.py script
 */
#include <pybind11/functional.h>
#include <popart/docs/opset6_docs.hpp>

#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include "../shared_cpp/np_utils.hpp"
#include "../shared_cpp/pyarray_accessor.hpp"

#include <popart/builder.hpp>
#include <popart/tensors.hpp>
#include <popart/version.hpp>

namespace py = pybind11;
using namespace popart;

PYBIND11_MODULE(popart_opset6, m) {
  py::class_<AiOnnxOpset6>(m, "AiOnnxOpset6")
      .def(
          "abs",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.abs(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, abs, opset6))
      .def(
          "add",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.add(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, add, opset6))
      .def(
          "logical_and",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_and(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, logical_and, opset6))
      .def(
          "argmax",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.argmax(args, axis, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 0,
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, argmax, opset6))
      .def(
          "argmin",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.argmin(args, axis, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 0,
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, argmin, opset6))
      .def(
          "averagepool",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.averagepool(
                args, kernel_shape, pads, strides, debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("pads")         = std::vector<int64_t>(),
          py::arg("strides")      = std::vector<int64_t>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, averagepool, opset6))
      .def(
          "batchnormalization",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             float epsilon,
             int64_t is_test,
             float momentum,
             int64_t spatial,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.batchnormalization(args,
                                            num_outputs,
                                            epsilon,
                                            is_test,
                                            momentum,
                                            spatial,
                                            debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("epsilon")      = 1e-05f,
          py::arg("is_test")      = 0,
          py::arg("momentum")     = 0.9f,
          py::arg("spatial")      = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, batchnormalization, opset6))
      .def(
          "cast",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::string &to,
             const DebugContext &debugContext) -> TensorId {
            return opset.cast(args, to, debugContext);
          },
          py::arg("args"),
          py::arg("to"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, cast, opset6))
      .def(
          "ceil",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.ceil(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, ceil, opset6))
      .def(
          "clip",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             float max,
             float min,
             const DebugContext &debugContext) -> TensorId {
            return opset.clip(args, max, min, debugContext);
          },
          py::arg("args"),
          py::arg("max")          = 3.4028234663852886e+38f,
          py::arg("min")          = -3.4028234663852886e+38f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, clip, opset6))
      .def(
          "concat",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.concat(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, concat, opset6))
      .def(
          "constant",
          [](AiOnnxOpset6 &opset,
             py::array array,
             const DebugContext &debugContext) {
            array = makeContiguous(array);
            ConstVoidData initData;
            initData.data = array.request().ptr;
            initData.info = getTensorInfo(array);
            return opset.constant(initData, debugContext);
          },
          py::arg("value"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, constant, opset6))
      .def(
          "conv",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &dilations,
             int64_t group,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.conv(args,
                              dilations,
                              group,
                              kernel_shape,
                              pads,
                              strides,
                              debugContext);
          },
          py::arg("args"),
          py::arg("dilations")    = std::vector<int64_t>(),
          py::arg("group")        = 1,
          py::arg("kernel_shape") = std::vector<int64_t>(),
          py::arg("pads")         = std::vector<int64_t>(),
          py::arg("strides")      = std::vector<int64_t>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, conv, opset6))
      .def(
          "convtranspose",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &dilations,
             int64_t group,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &output_padding,
             const std::vector<int64_t> &output_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.convtranspose(args,
                                       dilations,
                                       group,
                                       kernel_shape,
                                       output_padding,
                                       output_shape,
                                       pads,
                                       strides,
                                       debugContext);
          },
          py::arg("args"),
          py::arg("dilations")      = std::vector<int64_t>(),
          py::arg("group")          = 1,
          py::arg("kernel_shape")   = std::vector<int64_t>(),
          py::arg("output_padding") = std::vector<int64_t>(),
          py::arg("output_shape")   = std::vector<int64_t>(),
          py::arg("pads")           = std::vector<int64_t>(),
          py::arg("strides")        = std::vector<int64_t>(),
          py::arg("debugContext")   = std::string(),
          OPSET6_DOC(popart, convtranspose, opset6))
      .def(
          "depthtospace",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t blocksize,
             const DebugContext &debugContext) -> TensorId {
            return opset.depthtospace(args, blocksize, debugContext);
          },
          py::arg("args"),
          py::arg("blocksize"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, depthtospace, opset6))
      .def(
          "div",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.div(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, div, opset6))
      .def(
          "dropout",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             int64_t is_test,
             float ratio,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.dropout(
                args, num_outputs, is_test, ratio, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("is_test")      = 0,
          py::arg("ratio")        = 0.5f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, dropout, opset6))
      .def(
          "elu",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             const DebugContext &debugContext) -> TensorId {
            return opset.elu(args, alpha, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 1.0f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, elu, opset6))
      .def(
          "equal",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.equal(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, equal, opset6))
      .def(
          "exp",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.exp(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, exp, opset6))
      .def(
          "flatten",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.flatten(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, flatten, opset6))
      .def(
          "floor",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.floor(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, floor, opset6))
      .def(
          "gru",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             int64_t linear_before_reset,
             int64_t output_sequence,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.gru(args,
                             num_outputs,
                             activation_alpha,
                             activation_beta,
                             activations,
                             clip,
                             direction,
                             hidden_size,
                             linear_before_reset,
                             output_sequence,
                             debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha")    = std::vector<float>(),
          py::arg("activation_beta")     = std::vector<float>(),
          py::arg("activations")         = std::vector<std::string>(),
          py::arg("clip")                = nonstd::optional<float>(),
          py::arg("direction")           = "forward",
          py::arg("hidden_size")         = nonstd::optional<int64_t>(),
          py::arg("linear_before_reset") = 0,
          py::arg("output_sequence")     = 0,
          py::arg("debugContext")        = std::string(),
          OPSET6_DOC(popart, gru, opset6))
      .def(
          "gather",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.gather(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, gather, opset6))
      .def(
          "gemm",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float beta,
             int64_t broadcast,
             int64_t transA,
             int64_t transB,
             const DebugContext &debugContext) -> TensorId {
            return opset.gemm(
                args, alpha, beta, broadcast, transA, transB, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 1.0f,
          py::arg("beta")         = 1.0f,
          py::arg("broadcast")    = 0,
          py::arg("transA")       = 0,
          py::arg("transB")       = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, gemm, opset6))
      .def(
          "globalaveragepool",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.globalaveragepool(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, globalaveragepool, opset6))
      .def(
          "globallppool",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t p,
             const DebugContext &debugContext) -> TensorId {
            return opset.globallppool(args, p, debugContext);
          },
          py::arg("args"),
          py::arg("p")            = 2,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, globallppool, opset6))
      .def(
          "globalmaxpool",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.globalmaxpool(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, globalmaxpool, opset6))
      .def(
          "greater",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.greater(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, greater, opset6))
      .def(
          "hardsigmoid",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float beta,
             const DebugContext &debugContext) -> TensorId {
            return opset.hardsigmoid(args, alpha, beta, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 0.2f,
          py::arg("beta")         = 0.5f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, hardsigmoid, opset6))
      .def(
          "hardmax",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.hardmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, hardmax, opset6))
      .def(
          "identity",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.identity(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, identity, opset6))
      .def(
          "logical_if",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const Builder &else_branch,
             const Builder &then_branch,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.logical_if(
                args, num_outputs, else_branch, then_branch, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("else_branch"),
          py::arg("then_branch"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, logical_if, opset6))
      .def(
          "instancenormalization",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             float epsilon,
             const DebugContext &debugContext) -> TensorId {
            return opset.instancenormalization(args, epsilon, debugContext);
          },
          py::arg("args"),
          py::arg("epsilon")      = 1e-05f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, instancenormalization, opset6))
      .def(
          "lrn",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t size,
             float alpha,
             float beta,
             float bias,
             const DebugContext &debugContext) -> TensorId {
            return opset.lrn(args, size, alpha, beta, bias, debugContext);
          },
          py::arg("args"),
          py::arg("size"),
          py::arg("alpha")        = 0.0001f,
          py::arg("beta")         = 0.75f,
          py::arg("bias")         = 1.0f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, lrn, opset6))
      .def(
          "lstm",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             int64_t input_forget,
             int64_t output_sequence,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.lstm(args,
                              num_outputs,
                              activation_alpha,
                              activation_beta,
                              activations,
                              clip,
                              direction,
                              hidden_size,
                              input_forget,
                              output_sequence,
                              debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha") = std::vector<float>(),
          py::arg("activation_beta")  = std::vector<float>(),
          py::arg("activations")      = std::vector<std::string>(),
          py::arg("clip")             = nonstd::optional<float>(),
          py::arg("direction")        = "forward",
          py::arg("hidden_size")      = nonstd::optional<int64_t>(),
          py::arg("input_forget")     = 0,
          py::arg("output_sequence")  = 0,
          py::arg("debugContext")     = std::string(),
          OPSET6_DOC(popart, lstm, opset6))
      .def(
          "leakyrelu",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             const DebugContext &debugContext) -> TensorId {
            return opset.leakyrelu(args, alpha, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 0.01f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, leakyrelu, opset6))
      .def(
          "less",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.less(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, less, opset6))
      .def(
          "log",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.log(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, log, opset6))
      .def(
          "logsoftmax",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.logsoftmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, logsoftmax, opset6))
      .def(
          "loop",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const Builder &body,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.loop(args, num_outputs, body, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("body"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, loop, opset6))
      .def(
          "lpnormalization",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t p,
             const DebugContext &debugContext) -> TensorId {
            return opset.lpnormalization(args, axis, p, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = -1,
          py::arg("p")            = 2,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, lpnormalization, opset6))
      .def(
          "lppool",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             int64_t p,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.lppool(
                args, kernel_shape, p, pads, strides, debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("p")            = 2,
          py::arg("pads")         = std::vector<int64_t>(),
          py::arg("strides")      = std::vector<int64_t>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, lppool, opset6))
      .def(
          "matmul",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.matmul(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, matmul, opset6))
      .def(
          "max",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.max(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, max, opset6))
      .def(
          "maxpool",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.maxpool(
                args, kernel_shape, pads, strides, debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("pads")         = std::vector<int64_t>(),
          py::arg("strides")      = std::vector<int64_t>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, maxpool, opset6))
      .def(
          "maxroipool",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &pooled_shape,
             float spatial_scale,
             const DebugContext &debugContext) -> TensorId {
            return opset.maxroipool(
                args, pooled_shape, spatial_scale, debugContext);
          },
          py::arg("args"),
          py::arg("pooled_shape"),
          py::arg("spatial_scale") = 1.0f,
          py::arg("debugContext")  = std::string(),
          OPSET6_DOC(popart, maxroipool, opset6))
      .def(
          "mean",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.mean(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, mean, opset6))
      .def(
          "min",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.min(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, min, opset6))
      .def(
          "mul",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.mul(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, mul, opset6))
      .def(
          "neg",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.neg(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, neg, opset6))
      .def(
          "logical_not",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_not(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, logical_not, opset6))
      .def(
          "logical_or",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_or(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, logical_or, opset6))
      .def(
          "prelu",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.prelu(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, prelu, opset6))
      .def(
          "pad",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &pads,
             const std::string &mode,
             float value,
             const DebugContext &debugContext) -> TensorId {
            return opset.pad(args, pads, mode, value, debugContext);
          },
          py::arg("args"),
          py::arg("pads"),
          py::arg("mode")         = "constant",
          py::arg("value")        = 0.0f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, pad, opset6))
      .def(
          "pow",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.pow(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, pow, opset6))
      .def(
          "rnn",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             int64_t output_sequence,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.rnn(args,
                             num_outputs,
                             activation_alpha,
                             activation_beta,
                             activations,
                             clip,
                             direction,
                             hidden_size,
                             output_sequence,
                             debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha") = std::vector<float>(),
          py::arg("activation_beta")  = std::vector<float>(),
          py::arg("activations")      = std::vector<std::string>(),
          py::arg("clip")             = nonstd::optional<float>(),
          py::arg("direction")        = "forward",
          py::arg("hidden_size")      = nonstd::optional<int64_t>(),
          py::arg("output_sequence")  = 0,
          py::arg("debugContext")     = std::string(),
          OPSET6_DOC(popart, rnn, opset6))
      .def(
          "randomnormal",
          [](AiOnnxOpset6 &opset,
             const std::vector<int64_t> &shape,
             int64_t dtype,
             float mean,
             float scale,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomnormal(
                shape, dtype, mean, scale, seed, debugContext);
          },
          py::arg("shape"),
          py::arg("dtype")        = 1,
          py::arg("mean")         = 0.0f,
          py::arg("scale")        = 1.0f,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, randomnormal, opset6))
      .def(
          "randomnormallike",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> dtype,
             float mean,
             float scale,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomnormallike(
                args, dtype, mean, scale, seed, debugContext);
          },
          py::arg("args"),
          py::arg("dtype")        = nonstd::optional<int64_t>(),
          py::arg("mean")         = 0.0f,
          py::arg("scale")        = 1.0f,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, randomnormallike, opset6))
      .def(
          "randomuniform",
          [](AiOnnxOpset6 &opset,
             const std::vector<int64_t> &shape,
             int64_t dtype,
             float high,
             float low,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomuniform(
                shape, dtype, high, low, seed, debugContext);
          },
          py::arg("shape"),
          py::arg("dtype")        = 1,
          py::arg("high")         = 1.0f,
          py::arg("low")          = 0.0f,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, randomuniform, opset6))
      .def(
          "randomuniformlike",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> dtype,
             float high,
             float low,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomuniformlike(
                args, dtype, high, low, seed, debugContext);
          },
          py::arg("args"),
          py::arg("dtype")        = nonstd::optional<int64_t>(),
          py::arg("high")         = 1.0f,
          py::arg("low")          = 0.0f,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, randomuniformlike, opset6))
      .def(
          "reciprocal",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.reciprocal(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reciprocal, opset6))
      .def(
          "reducel1",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducel1(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducel1, opset6))
      .def(
          "reducel2",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducel2(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducel2, opset6))
      .def(
          "reducelogsum",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducelogsum(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducelogsum, opset6))
      .def(
          "reducelogsumexp",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducelogsumexp(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducelogsumexp, opset6))
      .def(
          "reducemax",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemax(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducemax, opset6))
      .def(
          "reducemean",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemean(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducemean, opset6))
      .def(
          "reducemin",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemin(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducemin, opset6))
      .def(
          "reduceprod",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reduceprod(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reduceprod, opset6))
      .def(
          "reducesum",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducesum(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducesum, opset6))
      .def(
          "reducesumsquare",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducesumsquare(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reducesumsquare, opset6))
      .def(
          "relu",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.relu(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, relu, opset6))
      .def(
          "reshape",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.reshape(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, reshape, opset6))
      .def(
          "selu",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float gamma,
             const DebugContext &debugContext) -> TensorId {
            return opset.selu(args, alpha, gamma, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 1.67326f,
          py::arg("gamma")        = 1.0507f,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, selu, opset6))
      .def(
          "shape",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.shape(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, shape, opset6))
      .def(
          "sigmoid",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sigmoid(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, sigmoid, opset6))
      .def(
          "size",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.size(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, size, opset6))
      .def(
          "slice",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &ends,
             const std::vector<int64_t> &starts,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.slice(args, ends, starts, axes, debugContext);
          },
          py::arg("args"),
          py::arg("ends"),
          py::arg("starts"),
          py::arg("axes")         = std::vector<int64_t>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, slice, opset6))
      .def(
          "softmax",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.softmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, softmax, opset6))
      .def(
          "softplus",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.softplus(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, softplus, opset6))
      .def(
          "softsign",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.softsign(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, softsign, opset6))
      .def(
          "spacetodepth",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t blocksize,
             const DebugContext &debugContext) -> TensorId {
            return opset.spacetodepth(args, blocksize, debugContext);
          },
          py::arg("args"),
          py::arg("blocksize"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, spacetodepth, opset6))
      .def(
          "split",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             int64_t axis,
             const std::vector<int64_t> &split,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.split(args, num_outputs, axis, split, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("axis")         = 0,
          py::arg("split")        = std::vector<int64_t>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, split, opset6))
      .def(
          "sqrt",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sqrt(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, sqrt, opset6))
      .def(
          "squeeze",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.squeeze(args, axes, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = std::vector<int64_t>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, squeeze, opset6))
      .def(
          "sub",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.sub(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, sub, opset6))
      .def(
          "sum",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sum(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, sum, opset6))
      .def(
          "tanh",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.tanh(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, tanh, opset6))
      .def(
          "tile",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.tile(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, tile, opset6))
      .def(
          "topk",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             int64_t k,
             int64_t axis,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.topk(args, k, axis, debugContext);
          },
          py::arg("args"),
          py::arg("k"),
          py::arg("axis")         = -1,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, topk, opset6))
      .def(
          "transpose",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &perm,
             const DebugContext &debugContext) -> TensorId {
            return opset.transpose(args, perm, debugContext);
          },
          py::arg("args"),
          py::arg("perm")         = std::vector<int64_t>(),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, transpose, opset6))
      .def(
          "unsqueeze",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.unsqueeze(args, axes, debugContext);
          },
          py::arg("args"),
          py::arg("axes"),
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, unsqueeze, opset6))
      .def(
          "upsample",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             float height_scale,
             float width_scale,
             const std::string &mode,
             const DebugContext &debugContext) -> TensorId {
            return opset.upsample(
                args, height_scale, width_scale, mode, debugContext);
          },
          py::arg("args"),
          py::arg("height_scale"),
          py::arg("width_scale"),
          py::arg("mode")         = "nearest",
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, upsample, opset6))
      .def(
          "logical_xor",
          [](AiOnnxOpset6 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> axis,
             int64_t broadcast,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_xor(args, axis, broadcast, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = nonstd::optional<int64_t>(),
          py::arg("broadcast")    = 0,
          py::arg("debugContext") = std::string(),
          OPSET6_DOC(popart, logical_xor, opset6));
}
