// Copyright (c) 2018 Graphcore Ltd. All rights reserved.
/*
 * THIS IS AN AUTOGENERATED FILE, DO NOT EDIT DIRECTLY
 *
 * To regenerate this file run the gen_operators.py script
 */
#include <pybind11/functional.h>

#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

#include "np_utils.hpp"
#include "pyarray_accessor.hpp"

#include <popart/builder.hpp>
#include <popart/tensors.hpp>
#include <popart/version.hpp>

#include <onnx/onnx_pb.h>

namespace py = pybind11;
using namespace popart;

PYBIND11_MODULE(popart_opset7, m) {
  py::class_<AiOnnxOpset7>(m, "AiOnnxOpset7")
      .def(
          "abs",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.abs(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "abs",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.abs(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "acos",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.acos(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "acos",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.acos(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "add",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.add(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "add",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.add(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "logical_and",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_and(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "logical_and",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_and(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "argmax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.argmax(args, axis, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 0,
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "argmax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.argmax(args, axis, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axis")        = 0,
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "argmin",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.argmin(args, axis, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 0,
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "argmin",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.argmin(args, axis, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axis")        = 0,
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "asin",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.asin(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "asin",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.asin(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "atan",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.atan(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "atan",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.atan(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "averagepool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             int64_t count_include_pad,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.averagepool(args,
                                     kernel_shape,
                                     count_include_pad,
                                     pads,
                                     strides,
                                     debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("count_include_pad") = 0,
          py::arg("pads")              = std::vector<int64_t>(),
          py::arg("strides")           = std::vector<int64_t>(),
          py::arg("debugContext")      = std::string())
      .def(
          "averagepool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             int64_t count_include_pad,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.averagepool(args,
                                     kernel_shape,
                                     count_include_pad,
                                     pads,
                                     strides,
                                     debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("count_include_pad") = 0,
          py::arg("pads")              = std::vector<int64_t>(),
          py::arg("strides")           = std::vector<int64_t>(),
          py::arg("debugPrefix")       = std::string())
      .def(
          "batchnormalization",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             float epsilon,
             float momentum,
             int64_t spatial,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.batchnormalization(
                args, num_outputs, epsilon, momentum, spatial, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("epsilon")      = 1e-05f,
          py::arg("momentum")     = 0.9f,
          py::arg("spatial")      = 1,
          py::arg("debugContext") = std::string())
      .def(
          "batchnormalization",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             float epsilon,
             float momentum,
             int64_t spatial,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.batchnormalization(
                args, num_outputs, epsilon, momentum, spatial, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("epsilon")     = 1e-05f,
          py::arg("momentum")    = 0.9f,
          py::arg("spatial")     = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "cast",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::string &to,
             const DebugContext &debugContext) -> TensorId {
            return opset.cast(args, to, debugContext);
          },
          py::arg("args"),
          py::arg("to"),
          py::arg("debugContext") = std::string())
      .def(
          "cast",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::string &to,
             const DebugContext &debugContext) -> TensorId {
            return opset.cast(args, to, debugContext);
          },
          py::arg("args"),
          py::arg("to"),
          py::arg("debugPrefix") = std::string())
      .def(
          "ceil",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.ceil(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "ceil",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.ceil(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "clip",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float max,
             float min,
             const DebugContext &debugContext) -> TensorId {
            return opset.clip(args, max, min, debugContext);
          },
          py::arg("args"),
          py::arg("max")          = 3.4028234663852886e+38f,
          py::arg("min")          = -3.4028234663852886e+38f,
          py::arg("debugContext") = std::string())
      .def(
          "clip",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float max,
             float min,
             const DebugContext &debugContext) -> TensorId {
            return opset.clip(args, max, min, debugContext);
          },
          py::arg("args"),
          py::arg("max")         = 3.4028234663852886e+38f,
          py::arg("min")         = -3.4028234663852886e+38f,
          py::arg("debugPrefix") = std::string())
      .def(
          "concat",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.concat(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis"),
          py::arg("debugContext") = std::string())
      .def(
          "concat",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.concat(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis"),
          py::arg("debugPrefix") = std::string())
      .def(
          "constant",
          [](AiOnnxOpset7 &opset,
             py::array array,
             const DebugContext &debugContext) {
            array = makeContiguous(array);
            ConstVoidData initData;
            initData.data = array.request().ptr;
            initData.info = getTensorInfo(array);
            return opset.constant(initData, debugContext);
          },
          py::arg("value"),
          py::arg("debugContext") = std::string())
      .def(
          "constant",
          [](AiOnnxOpset7 &opset,
             py::array array,
             const DebugContext &debugContext) {
            array = makeContiguous(array);
            ConstVoidData initData;
            initData.data = array.request().ptr;
            initData.info = getTensorInfo(array);
            return opset.constant(initData, debugContext);
          },
          py::arg("value"),
          py::arg("debugPrefix") = std::string())
      .def(
          "conv",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &dilations,
             int64_t group,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.conv(args,
                              dilations,
                              group,
                              kernel_shape,
                              pads,
                              strides,
                              debugContext);
          },
          py::arg("args"),
          py::arg("dilations")    = std::vector<int64_t>(),
          py::arg("group")        = 1,
          py::arg("kernel_shape") = std::vector<int64_t>(),
          py::arg("pads")         = std::vector<int64_t>(),
          py::arg("strides")      = std::vector<int64_t>(),
          py::arg("debugContext") = std::string())
      .def(
          "conv",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &dilations,
             int64_t group,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.conv(args,
                              dilations,
                              group,
                              kernel_shape,
                              pads,
                              strides,
                              debugContext);
          },
          py::arg("args"),
          py::arg("dilations")    = std::vector<int64_t>(),
          py::arg("group")        = 1,
          py::arg("kernel_shape") = std::vector<int64_t>(),
          py::arg("pads")         = std::vector<int64_t>(),
          py::arg("strides")      = std::vector<int64_t>(),
          py::arg("debugPrefix")  = std::string())
      .def(
          "convtranspose",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &dilations,
             int64_t group,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &output_padding,
             const std::vector<int64_t> &output_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.convtranspose(args,
                                       dilations,
                                       group,
                                       kernel_shape,
                                       output_padding,
                                       output_shape,
                                       pads,
                                       strides,
                                       debugContext);
          },
          py::arg("args"),
          py::arg("dilations")      = std::vector<int64_t>(),
          py::arg("group")          = 1,
          py::arg("kernel_shape")   = std::vector<int64_t>(),
          py::arg("output_padding") = std::vector<int64_t>(),
          py::arg("output_shape")   = std::vector<int64_t>(),
          py::arg("pads")           = std::vector<int64_t>(),
          py::arg("strides")        = std::vector<int64_t>(),
          py::arg("debugContext")   = std::string())
      .def(
          "convtranspose",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &dilations,
             int64_t group,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &output_padding,
             const std::vector<int64_t> &output_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.convtranspose(args,
                                       dilations,
                                       group,
                                       kernel_shape,
                                       output_padding,
                                       output_shape,
                                       pads,
                                       strides,
                                       debugContext);
          },
          py::arg("args"),
          py::arg("dilations")      = std::vector<int64_t>(),
          py::arg("group")          = 1,
          py::arg("kernel_shape")   = std::vector<int64_t>(),
          py::arg("output_padding") = std::vector<int64_t>(),
          py::arg("output_shape")   = std::vector<int64_t>(),
          py::arg("pads")           = std::vector<int64_t>(),
          py::arg("strides")        = std::vector<int64_t>(),
          py::arg("debugPrefix")    = std::string())
      .def(
          "cos",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.cos(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "cos",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.cos(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "depthtospace",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t blocksize,
             const DebugContext &debugContext) -> TensorId {
            return opset.depthtospace(args, blocksize, debugContext);
          },
          py::arg("args"),
          py::arg("blocksize"),
          py::arg("debugContext") = std::string())
      .def(
          "depthtospace",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t blocksize,
             const DebugContext &debugContext) -> TensorId {
            return opset.depthtospace(args, blocksize, debugContext);
          },
          py::arg("args"),
          py::arg("blocksize"),
          py::arg("debugPrefix") = std::string())
      .def(
          "div",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.div(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "div",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.div(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "dropout",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             float ratio,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.dropout(args, num_outputs, ratio, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("ratio")        = 0.5f,
          py::arg("debugContext") = std::string())
      .def(
          "dropout",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             float ratio,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.dropout(args, num_outputs, ratio, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("ratio")       = 0.5f,
          py::arg("debugPrefix") = std::string())
      .def(
          "elu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             const DebugContext &debugContext) -> TensorId {
            return opset.elu(args, alpha, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 1.0f,
          py::arg("debugContext") = std::string())
      .def(
          "elu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             const DebugContext &debugContext) -> TensorId {
            return opset.elu(args, alpha, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")       = 1.0f,
          py::arg("debugPrefix") = std::string())
      .def(
          "equal",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.equal(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "equal",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.equal(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "exp",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.exp(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "exp",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.exp(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "flatten",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.flatten(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 1,
          py::arg("debugContext") = std::string())
      .def(
          "flatten",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.flatten(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")        = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "floor",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.floor(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "floor",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.floor(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "gru",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             int64_t linear_before_reset,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.gru(args,
                             num_outputs,
                             activation_alpha,
                             activation_beta,
                             activations,
                             clip,
                             direction,
                             hidden_size,
                             linear_before_reset,
                             debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha")    = std::vector<float>(),
          py::arg("activation_beta")     = std::vector<float>(),
          py::arg("activations")         = std::vector<std::string>(),
          py::arg("clip")                = nonstd::optional<float>(),
          py::arg("direction")           = "forward",
          py::arg("hidden_size")         = nonstd::optional<int64_t>(),
          py::arg("linear_before_reset") = 0,
          py::arg("debugContext")        = std::string())
      .def(
          "gru",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             int64_t linear_before_reset,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.gru(args,
                             num_outputs,
                             activation_alpha,
                             activation_beta,
                             activations,
                             clip,
                             direction,
                             hidden_size,
                             linear_before_reset,
                             debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha")    = std::vector<float>(),
          py::arg("activation_beta")     = std::vector<float>(),
          py::arg("activations")         = std::vector<std::string>(),
          py::arg("clip")                = nonstd::optional<float>(),
          py::arg("direction")           = "forward",
          py::arg("hidden_size")         = nonstd::optional<int64_t>(),
          py::arg("linear_before_reset") = 0,
          py::arg("debugPrefix")         = std::string())
      .def(
          "gather",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.gather(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 0,
          py::arg("debugContext") = std::string())
      .def(
          "gather",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.gather(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")        = 0,
          py::arg("debugPrefix") = std::string())
      .def(
          "gemm",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float beta,
             int64_t transA,
             int64_t transB,
             const DebugContext &debugContext) -> TensorId {
            return opset.gemm(args, alpha, beta, transA, transB, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 1.0f,
          py::arg("beta")         = 1.0f,
          py::arg("transA")       = 0,
          py::arg("transB")       = 0,
          py::arg("debugContext") = std::string())
      .def(
          "gemm",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float beta,
             int64_t transA,
             int64_t transB,
             const DebugContext &debugContext) -> TensorId {
            return opset.gemm(args, alpha, beta, transA, transB, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")       = 1.0f,
          py::arg("beta")        = 1.0f,
          py::arg("transA")      = 0,
          py::arg("transB")      = 0,
          py::arg("debugPrefix") = std::string())
      .def(
          "globalaveragepool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.globalaveragepool(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "globalaveragepool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.globalaveragepool(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "globallppool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t p,
             const DebugContext &debugContext) -> TensorId {
            return opset.globallppool(args, p, debugContext);
          },
          py::arg("args"),
          py::arg("p")            = 2,
          py::arg("debugContext") = std::string())
      .def(
          "globallppool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t p,
             const DebugContext &debugContext) -> TensorId {
            return opset.globallppool(args, p, debugContext);
          },
          py::arg("args"),
          py::arg("p")           = 2,
          py::arg("debugPrefix") = std::string())
      .def(
          "globalmaxpool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.globalmaxpool(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "globalmaxpool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.globalmaxpool(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "greater",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.greater(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "greater",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.greater(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "hardsigmoid",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float beta,
             const DebugContext &debugContext) -> TensorId {
            return opset.hardsigmoid(args, alpha, beta, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 0.2f,
          py::arg("beta")         = 0.5f,
          py::arg("debugContext") = std::string())
      .def(
          "hardsigmoid",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float beta,
             const DebugContext &debugContext) -> TensorId {
            return opset.hardsigmoid(args, alpha, beta, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")       = 0.2f,
          py::arg("beta")        = 0.5f,
          py::arg("debugPrefix") = std::string())
      .def(
          "hardmax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.hardmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 1,
          py::arg("debugContext") = std::string())
      .def(
          "hardmax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.hardmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")        = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "identity",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.identity(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "identity",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.identity(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "logical_if",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const Builder &else_branch,
             const Builder &then_branch,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.logical_if(
                args, num_outputs, else_branch, then_branch, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("else_branch"),
          py::arg("then_branch"),
          py::arg("debugContext") = std::string())
      .def(
          "logical_if",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const Builder &else_branch,
             const Builder &then_branch,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.logical_if(
                args, num_outputs, else_branch, then_branch, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("else_branch"),
          py::arg("then_branch"),
          py::arg("debugPrefix") = std::string())
      .def(
          "instancenormalization",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float epsilon,
             const DebugContext &debugContext) -> TensorId {
            return opset.instancenormalization(args, epsilon, debugContext);
          },
          py::arg("args"),
          py::arg("epsilon")      = 1e-05f,
          py::arg("debugContext") = std::string())
      .def(
          "instancenormalization",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float epsilon,
             const DebugContext &debugContext) -> TensorId {
            return opset.instancenormalization(args, epsilon, debugContext);
          },
          py::arg("args"),
          py::arg("epsilon")     = 1e-05f,
          py::arg("debugPrefix") = std::string())
      .def(
          "lrn",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t size,
             float alpha,
             float beta,
             float bias,
             const DebugContext &debugContext) -> TensorId {
            return opset.lrn(args, size, alpha, beta, bias, debugContext);
          },
          py::arg("args"),
          py::arg("size"),
          py::arg("alpha")        = 0.0001f,
          py::arg("beta")         = 0.75f,
          py::arg("bias")         = 1.0f,
          py::arg("debugContext") = std::string())
      .def(
          "lrn",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t size,
             float alpha,
             float beta,
             float bias,
             const DebugContext &debugContext) -> TensorId {
            return opset.lrn(args, size, alpha, beta, bias, debugContext);
          },
          py::arg("args"),
          py::arg("size"),
          py::arg("alpha")       = 0.0001f,
          py::arg("beta")        = 0.75f,
          py::arg("bias")        = 1.0f,
          py::arg("debugPrefix") = std::string())
      .def(
          "lstm",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             int64_t input_forget,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.lstm(args,
                              num_outputs,
                              activation_alpha,
                              activation_beta,
                              activations,
                              clip,
                              direction,
                              hidden_size,
                              input_forget,
                              debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha") = std::vector<float>(),
          py::arg("activation_beta")  = std::vector<float>(),
          py::arg("activations")      = std::vector<std::string>(),
          py::arg("clip")             = nonstd::optional<float>(),
          py::arg("direction")        = "forward",
          py::arg("hidden_size")      = nonstd::optional<int64_t>(),
          py::arg("input_forget")     = 0,
          py::arg("debugContext")     = std::string())
      .def(
          "lstm",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             int64_t input_forget,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.lstm(args,
                              num_outputs,
                              activation_alpha,
                              activation_beta,
                              activations,
                              clip,
                              direction,
                              hidden_size,
                              input_forget,
                              debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha") = std::vector<float>(),
          py::arg("activation_beta")  = std::vector<float>(),
          py::arg("activations")      = std::vector<std::string>(),
          py::arg("clip")             = nonstd::optional<float>(),
          py::arg("direction")        = "forward",
          py::arg("hidden_size")      = nonstd::optional<int64_t>(),
          py::arg("input_forget")     = 0,
          py::arg("debugPrefix")      = std::string())
      .def(
          "leakyrelu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             const DebugContext &debugContext) -> TensorId {
            return opset.leakyrelu(args, alpha, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 0.01f,
          py::arg("debugContext") = std::string())
      .def(
          "leakyrelu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             const DebugContext &debugContext) -> TensorId {
            return opset.leakyrelu(args, alpha, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")       = 0.01f,
          py::arg("debugPrefix") = std::string())
      .def(
          "less",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.less(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "less",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.less(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "log",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.log(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "log",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.log(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "logsoftmax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.logsoftmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 1,
          py::arg("debugContext") = std::string())
      .def(
          "logsoftmax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.logsoftmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")        = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "loop",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const Builder &body,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.loop(args, num_outputs, body, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("body"),
          py::arg("debugContext") = std::string())
      .def(
          "loop",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const Builder &body,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.loop(args, num_outputs, body, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("body"),
          py::arg("debugPrefix") = std::string())
      .def(
          "lpnormalization",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t p,
             const DebugContext &debugContext) -> TensorId {
            return opset.lpnormalization(args, axis, p, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = -1,
          py::arg("p")            = 2,
          py::arg("debugContext") = std::string())
      .def(
          "lpnormalization",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             int64_t p,
             const DebugContext &debugContext) -> TensorId {
            return opset.lpnormalization(args, axis, p, debugContext);
          },
          py::arg("args"),
          py::arg("axis")        = -1,
          py::arg("p")           = 2,
          py::arg("debugPrefix") = std::string())
      .def(
          "lppool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             int64_t p,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.lppool(
                args, kernel_shape, p, pads, strides, debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("p")            = 2,
          py::arg("pads")         = std::vector<int64_t>(),
          py::arg("strides")      = std::vector<int64_t>(),
          py::arg("debugContext") = std::string())
      .def(
          "lppool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             int64_t p,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.lppool(
                args, kernel_shape, p, pads, strides, debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("p")           = 2,
          py::arg("pads")        = std::vector<int64_t>(),
          py::arg("strides")     = std::vector<int64_t>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "matmul",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.matmul(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "matmul",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.matmul(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "max",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.max(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "max",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.max(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "maxpool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.maxpool(
                args, kernel_shape, pads, strides, debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("pads")         = std::vector<int64_t>(),
          py::arg("strides")      = std::vector<int64_t>(),
          py::arg("debugContext") = std::string())
      .def(
          "maxpool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &kernel_shape,
             const std::vector<int64_t> &pads,
             const std::vector<int64_t> &strides,
             const DebugContext &debugContext) -> TensorId {
            return opset.maxpool(
                args, kernel_shape, pads, strides, debugContext);
          },
          py::arg("args"),
          py::arg("kernel_shape"),
          py::arg("pads")        = std::vector<int64_t>(),
          py::arg("strides")     = std::vector<int64_t>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "maxroipool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &pooled_shape,
             float spatial_scale,
             const DebugContext &debugContext) -> TensorId {
            return opset.maxroipool(
                args, pooled_shape, spatial_scale, debugContext);
          },
          py::arg("args"),
          py::arg("pooled_shape"),
          py::arg("spatial_scale") = 1.0f,
          py::arg("debugContext")  = std::string())
      .def(
          "maxroipool",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &pooled_shape,
             float spatial_scale,
             const DebugContext &debugContext) -> TensorId {
            return opset.maxroipool(
                args, pooled_shape, spatial_scale, debugContext);
          },
          py::arg("args"),
          py::arg("pooled_shape"),
          py::arg("spatial_scale") = 1.0f,
          py::arg("debugPrefix")   = std::string())
      .def(
          "mean",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.mean(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "mean",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.mean(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "min",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.min(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "min",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.min(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "mul",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.mul(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "mul",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.mul(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "multinomial",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t dtype,
             int64_t sample_size,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.multinomial(
                args, dtype, sample_size, seed, debugContext);
          },
          py::arg("args"),
          py::arg("dtype")        = 6,
          py::arg("sample_size")  = 1,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string())
      .def(
          "multinomial",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t dtype,
             int64_t sample_size,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.multinomial(
                args, dtype, sample_size, seed, debugContext);
          },
          py::arg("args"),
          py::arg("dtype")       = 6,
          py::arg("sample_size") = 1,
          py::arg("seed")        = nonstd::optional<float>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "neg",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.neg(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "neg",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.neg(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "logical_not",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_not(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "logical_not",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_not(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "logical_or",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_or(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "logical_or",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_or(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "prelu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.prelu(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "prelu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.prelu(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "pad",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &pads,
             const std::string &mode,
             float value,
             const DebugContext &debugContext) -> TensorId {
            return opset.pad(args, pads, mode, value, debugContext);
          },
          py::arg("args"),
          py::arg("pads"),
          py::arg("mode")         = "constant",
          py::arg("value")        = 0.0f,
          py::arg("debugContext") = std::string())
      .def(
          "pad",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &pads,
             const std::string &mode,
             float value,
             const DebugContext &debugContext) -> TensorId {
            return opset.pad(args, pads, mode, value, debugContext);
          },
          py::arg("args"),
          py::arg("pads"),
          py::arg("mode")        = "constant",
          py::arg("value")       = 0.0f,
          py::arg("debugPrefix") = std::string())
      .def(
          "pow",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.pow(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "pow",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.pow(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "rnn",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.rnn(args,
                             num_outputs,
                             activation_alpha,
                             activation_beta,
                             activations,
                             clip,
                             direction,
                             hidden_size,
                             debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha") = std::vector<float>(),
          py::arg("activation_beta")  = std::vector<float>(),
          py::arg("activations")      = std::vector<std::string>(),
          py::arg("clip")             = nonstd::optional<float>(),
          py::arg("direction")        = "forward",
          py::arg("hidden_size")      = nonstd::optional<int64_t>(),
          py::arg("debugContext")     = std::string())
      .def(
          "rnn",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             const std::vector<float> &activation_alpha,
             const std::vector<float> &activation_beta,
             const std::vector<std::string> &activations,
             nonstd::optional<float> clip,
             const std::string &direction,
             nonstd::optional<int64_t> hidden_size,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.rnn(args,
                             num_outputs,
                             activation_alpha,
                             activation_beta,
                             activations,
                             clip,
                             direction,
                             hidden_size,
                             debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("activation_alpha") = std::vector<float>(),
          py::arg("activation_beta")  = std::vector<float>(),
          py::arg("activations")      = std::vector<std::string>(),
          py::arg("clip")             = nonstd::optional<float>(),
          py::arg("direction")        = "forward",
          py::arg("hidden_size")      = nonstd::optional<int64_t>(),
          py::arg("debugPrefix")      = std::string())
      .def(
          "randomnormal",
          [](AiOnnxOpset7 &opset,
             const std::vector<int64_t> &shape,
             int64_t dtype,
             float mean,
             float scale,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomnormal(
                shape, dtype, mean, scale, seed, debugContext);
          },
          py::arg("shape"),
          py::arg("dtype")        = 1,
          py::arg("mean")         = 0.0f,
          py::arg("scale")        = 1.0f,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string())
      .def(
          "randomnormal",
          [](AiOnnxOpset7 &opset,
             const std::vector<int64_t> &shape,
             int64_t dtype,
             float mean,
             float scale,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomnormal(
                shape, dtype, mean, scale, seed, debugContext);
          },
          py::arg("shape"),
          py::arg("dtype")       = 1,
          py::arg("mean")        = 0.0f,
          py::arg("scale")       = 1.0f,
          py::arg("seed")        = nonstd::optional<float>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "randomnormallike",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> dtype,
             float mean,
             float scale,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomnormallike(
                args, dtype, mean, scale, seed, debugContext);
          },
          py::arg("args"),
          py::arg("dtype")        = nonstd::optional<int64_t>(),
          py::arg("mean")         = 0.0f,
          py::arg("scale")        = 1.0f,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string())
      .def(
          "randomnormallike",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> dtype,
             float mean,
             float scale,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomnormallike(
                args, dtype, mean, scale, seed, debugContext);
          },
          py::arg("args"),
          py::arg("dtype")       = nonstd::optional<int64_t>(),
          py::arg("mean")        = 0.0f,
          py::arg("scale")       = 1.0f,
          py::arg("seed")        = nonstd::optional<float>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "randomuniform",
          [](AiOnnxOpset7 &opset,
             const std::vector<int64_t> &shape,
             int64_t dtype,
             float high,
             float low,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomuniform(
                shape, dtype, high, low, seed, debugContext);
          },
          py::arg("shape"),
          py::arg("dtype")        = 1,
          py::arg("high")         = 1.0f,
          py::arg("low")          = 0.0f,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string())
      .def(
          "randomuniform",
          [](AiOnnxOpset7 &opset,
             const std::vector<int64_t> &shape,
             int64_t dtype,
             float high,
             float low,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomuniform(
                shape, dtype, high, low, seed, debugContext);
          },
          py::arg("shape"),
          py::arg("dtype")       = 1,
          py::arg("high")        = 1.0f,
          py::arg("low")         = 0.0f,
          py::arg("seed")        = nonstd::optional<float>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "randomuniformlike",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> dtype,
             float high,
             float low,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomuniformlike(
                args, dtype, high, low, seed, debugContext);
          },
          py::arg("args"),
          py::arg("dtype")        = nonstd::optional<int64_t>(),
          py::arg("high")         = 1.0f,
          py::arg("low")          = 0.0f,
          py::arg("seed")         = nonstd::optional<float>(),
          py::arg("debugContext") = std::string())
      .def(
          "randomuniformlike",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<int64_t> dtype,
             float high,
             float low,
             nonstd::optional<float> seed,
             const DebugContext &debugContext) -> TensorId {
            return opset.randomuniformlike(
                args, dtype, high, low, seed, debugContext);
          },
          py::arg("args"),
          py::arg("dtype")       = nonstd::optional<int64_t>(),
          py::arg("high")        = 1.0f,
          py::arg("low")         = 0.0f,
          py::arg("seed")        = nonstd::optional<float>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "reciprocal",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.reciprocal(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "reciprocal",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.reciprocal(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "reducel1",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducel1(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducel1",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducel1(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reducel2",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducel2(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducel2",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducel2(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reducelogsum",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducelogsum(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducelogsum",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducelogsum(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reducelogsumexp",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducelogsumexp(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducelogsumexp",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducelogsumexp(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reducemax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemax(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducemax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemax(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reducemean",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemean(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducemean",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemean(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reducemin",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemin(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducemin",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducemin(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reduceprod",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reduceprod(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reduceprod",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reduceprod(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reducesum",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducesum(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducesum",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducesum(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "reducesumsquare",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducesumsquare(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")     = 1,
          py::arg("debugContext") = std::string())
      .def(
          "reducesumsquare",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             nonstd::optional<std::vector<int64_t>> axes,
             int64_t keepdims,
             const DebugContext &debugContext) -> TensorId {
            return opset.reducesumsquare(args, axes, keepdims, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = nonstd::optional<std::vector<int64_t>>(),
          py::arg("keepdims")    = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "relu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.relu(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "relu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.relu(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "reshape",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.reshape(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "reshape",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.reshape(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "selu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float gamma,
             const DebugContext &debugContext) -> TensorId {
            return opset.selu(args, alpha, gamma, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")        = 1.67326f,
          py::arg("gamma")        = 1.0507f,
          py::arg("debugContext") = std::string())
      .def(
          "selu",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             float alpha,
             float gamma,
             const DebugContext &debugContext) -> TensorId {
            return opset.selu(args, alpha, gamma, debugContext);
          },
          py::arg("args"),
          py::arg("alpha")       = 1.67326f,
          py::arg("gamma")       = 1.0507f,
          py::arg("debugPrefix") = std::string())
      .def(
          "shape",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.shape(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "shape",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.shape(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "sigmoid",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sigmoid(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "sigmoid",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sigmoid(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "sin",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sin(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "sin",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sin(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "size",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.size(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "size",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.size(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "slice",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &ends,
             const std::vector<int64_t> &starts,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.slice(args, ends, starts, axes, debugContext);
          },
          py::arg("args"),
          py::arg("ends"),
          py::arg("starts"),
          py::arg("axes")         = std::vector<int64_t>(),
          py::arg("debugContext") = std::string())
      .def(
          "slice",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &ends,
             const std::vector<int64_t> &starts,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.slice(args, ends, starts, axes, debugContext);
          },
          py::arg("args"),
          py::arg("ends"),
          py::arg("starts"),
          py::arg("axes")        = std::vector<int64_t>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "softmax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.softmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")         = 1,
          py::arg("debugContext") = std::string())
      .def(
          "softmax",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t axis,
             const DebugContext &debugContext) -> TensorId {
            return opset.softmax(args, axis, debugContext);
          },
          py::arg("args"),
          py::arg("axis")        = 1,
          py::arg("debugPrefix") = std::string())
      .def(
          "softplus",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.softplus(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "softplus",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.softplus(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "softsign",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.softsign(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "softsign",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.softsign(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "spacetodepth",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t blocksize,
             const DebugContext &debugContext) -> TensorId {
            return opset.spacetodepth(args, blocksize, debugContext);
          },
          py::arg("args"),
          py::arg("blocksize"),
          py::arg("debugContext") = std::string())
      .def(
          "spacetodepth",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t blocksize,
             const DebugContext &debugContext) -> TensorId {
            return opset.spacetodepth(args, blocksize, debugContext);
          },
          py::arg("args"),
          py::arg("blocksize"),
          py::arg("debugPrefix") = std::string())
      .def(
          "split",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             int64_t axis,
             const std::vector<int64_t> &split,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.split(args, num_outputs, axis, split, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("axis")         = 0,
          py::arg("split")        = std::vector<int64_t>(),
          py::arg("debugContext") = std::string())
      .def(
          "split",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             unsigned num_outputs,
             int64_t axis,
             const std::vector<int64_t> &split,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.split(args, num_outputs, axis, split, debugContext);
          },
          py::arg("args"),
          py::arg("num_outputs"),
          py::arg("axis")        = 0,
          py::arg("split")       = std::vector<int64_t>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "sqrt",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sqrt(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "sqrt",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sqrt(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "squeeze",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.squeeze(args, axes, debugContext);
          },
          py::arg("args"),
          py::arg("axes")         = std::vector<int64_t>(),
          py::arg("debugContext") = std::string())
      .def(
          "squeeze",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.squeeze(args, axes, debugContext);
          },
          py::arg("args"),
          py::arg("axes")        = std::vector<int64_t>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "sub",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sub(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "sub",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sub(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "sum",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sum(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "sum",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.sum(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "tan",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.tan(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "tan",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.tan(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "tanh",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.tanh(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "tanh",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.tanh(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "tile",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.tile(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "tile",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.tile(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string())
      .def(
          "topk",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t k,
             int64_t axis,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.topk(args, k, axis, debugContext);
          },
          py::arg("args"),
          py::arg("k"),
          py::arg("axis")         = -1,
          py::arg("debugContext") = std::string())
      .def(
          "topk",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             int64_t k,
             int64_t axis,
             const DebugContext &debugContext) -> std::vector<TensorId> {
            return opset.topk(args, k, axis, debugContext);
          },
          py::arg("args"),
          py::arg("k"),
          py::arg("axis")        = -1,
          py::arg("debugPrefix") = std::string())
      .def(
          "transpose",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &perm,
             const DebugContext &debugContext) -> TensorId {
            return opset.transpose(args, perm, debugContext);
          },
          py::arg("args"),
          py::arg("perm")         = std::vector<int64_t>(),
          py::arg("debugContext") = std::string())
      .def(
          "transpose",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &perm,
             const DebugContext &debugContext) -> TensorId {
            return opset.transpose(args, perm, debugContext);
          },
          py::arg("args"),
          py::arg("perm")        = std::vector<int64_t>(),
          py::arg("debugPrefix") = std::string())
      .def(
          "unsqueeze",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.unsqueeze(args, axes, debugContext);
          },
          py::arg("args"),
          py::arg("axes"),
          py::arg("debugContext") = std::string())
      .def(
          "unsqueeze",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<int64_t> &axes,
             const DebugContext &debugContext) -> TensorId {
            return opset.unsqueeze(args, axes, debugContext);
          },
          py::arg("args"),
          py::arg("axes"),
          py::arg("debugPrefix") = std::string())
      .def(
          "upsample",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<float> &scales,
             const std::string &mode,
             const DebugContext &debugContext) -> TensorId {
            return opset.upsample(args, scales, mode, debugContext);
          },
          py::arg("args"),
          py::arg("scales"),
          py::arg("mode")         = "nearest",
          py::arg("debugContext") = std::string())
      .def(
          "upsample",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const std::vector<float> &scales,
             const std::string &mode,
             const DebugContext &debugContext) -> TensorId {
            return opset.upsample(args, scales, mode, debugContext);
          },
          py::arg("args"),
          py::arg("scales"),
          py::arg("mode")        = "nearest",
          py::arg("debugPrefix") = std::string())
      .def(
          "logical_xor",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_xor(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugContext") = std::string())
      .def(
          "logical_xor",
          [](AiOnnxOpset7 &opset,
             const std::vector<TensorId> &args,
             const DebugContext &debugContext) -> TensorId {
            return opset.logical_xor(args, debugContext);
          },
          py::arg("args"),
          py::arg("debugPrefix") = std::string());
}
