<?php
// Copyright (c) 2021 Graphcore Ltd. All rights reserved.

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'AutoPatchLinter' => 'AutoPatchLinter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'AutoPatchLinter' => 'ArcanistExternalLinter',
  ),
));
